#!/usr/bin/env python3
"""TRUMP contextual M2R Slime R2.

R2 replaces fixed whole-formula champion order with a fresh source-only ranking
of the *current residual* each time C025 asks for a pivot order.  The policy is
frozen in TRUMP_SLIME_CONTEXTUAL_M2R_R2_FROZEN_BENCH_V1.json.

The primary feature is a proof-carrying upper bound on raw elimination units:

  retained_units + |P_v|*|N_v| * (1 + max_pos_tail + max_neg_tail)

Every actual non-tautological resolvent is generated by one positive/negative
parent pair and has width no greater than the two parent tails combined.
Counting all pairs even when tautological or duplicate can only overestimate
raw units.  Therefore upper<=state_cap certifies cap safety, but upper>cap says
nothing negative.

The Slime changes proposal order only. Exact eliminate_var_capped and replay
remain authority. P_VS_NP remains OPEN.
"""
from __future__ import annotations

from contextlib import contextmanager
import json
from pathlib import Path
from types import ModuleType
from typing import Any, Iterator, Sequence

from trump_candidate import (
    TrumpCandidateError,
    fetch_source_bytes,
    import_candidate_module,
    load_manifest,
    primary_source,
)

HERE = Path(__file__).resolve().parent
SPEC_PATH = HERE / "TRUMP_SLIME_CONTEXTUAL_M2R_R2_FROZEN_BENCH_V1.json"


class ContextualM2RError(RuntimeError):
    pass


def load_frozen_spec() -> dict[str, Any]:
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    if spec.get("benchmark_id") != "JANUS_TRUMP_SLIME_CONTEXTUAL_M2R_R2_FROZEN_C1K0_BENCH_V1":
        raise ContextualM2RError("FROZEN_SPEC_ID_DRIFT")
    if spec.get("winner_preregistered") is not False:
        raise ContextualM2RError("WINNER_PREREGISTRATION_FORBIDDEN")
    return spec


def load_pinned_solver() -> tuple[ModuleType, dict[str, Any]]:
    manifest = load_manifest()
    source = primary_source(manifest)
    spec = load_frozen_spec()
    expected = spec["solver"]
    if (
        source.get("repository") != expected.get("repository")
        or source.get("pinned_commit") != expected.get("commit")
        or source.get("path") != expected.get("path")
        or source.get("git_blob_sha") != expected.get("git_blob_sha")
    ):
        raise ContextualM2RError("PINNED_SOLVER_DRIFT")
    data = fetch_source_bytes(source)
    return import_candidate_module(data, source), source


def contextual_features(
    cnf: Sequence[Sequence[int]],
    canonical_pivots: Sequence[int],
    *,
    state_cap: int,
) -> tuple[list[dict[str, Any]], int]:
    """Compute the frozen R2 per-pivot source-only risk rows and charged work."""
    pivots = [int(v) for v in canonical_pivots]
    if len(set(pivots)) != len(pivots):
        raise ContextualM2RError("DUPLICATE_CANONICAL_PIVOT")
    live = set(pivots)
    stats = {
        v: {
            "positive": 0,
            "negative": 0,
            "incident_units": 0,
            "max_positive_tail": 0,
            "max_negative_tail": 0,
        }
        for v in pivots
    }
    total_units = 0
    literal_updates = 0
    clause_scan_units = 0
    for clause in cnf:
        width = len(clause)
        units = 1 + width
        total_units += units
        clause_scan_units += units
        for raw_lit in clause:
            lit = int(raw_lit)
            v = abs(lit)
            if v not in live:
                continue
            literal_updates += 1
            row = stats[v]
            row["incident_units"] += units
            if lit > 0:
                row["positive"] += 1
                row["max_positive_tail"] = max(row["max_positive_tail"], width - 1)
            else:
                row["negative"] += 1
                row["max_negative_tail"] = max(row["max_negative_tail"], width - 1)

    rows: list[dict[str, Any]] = []
    for index, v in enumerate(pivots):
        s = stats[v]
        positive = int(s["positive"])
        negative = int(s["negative"])
        pairs = positive * negative
        retained_units = total_units - int(s["incident_units"])
        max_resolvent_width_upper = (
            int(s["max_positive_tail"]) + int(s["max_negative_tail"])
            if pairs else 0
        )
        certified_upper = retained_units + pairs * (1 + max_resolvent_width_upper)
        safe = certified_upper <= int(state_cap)
        rows.append({
            "var": v,
            "canonical_index": index,
            "positive": positive,
            "negative": negative,
            "incident_units": int(s["incident_units"]),
            "retained_units": retained_units,
            "parent_pairs": pairs,
            "max_positive_tail": int(s["max_positive_tail"]),
            "max_negative_tail": int(s["max_negative_tail"]),
            "max_resolvent_width_upper": max_resolvent_width_upper,
            "certified_raw_upper_units": certified_upper,
            "certified_cap_safe": safe,
            "rank_tuple": [0 if safe else 1, certified_upper, pairs, index],
        })

    # Frozen conservative accounting contract. It intentionally charges more
    # than Python instruction count precision can justify; there is no free Slime.
    feature_work = clause_scan_units + 4 * literal_updates + 8 * len(pivots)
    return rows, int(feature_work)


def rank_contextual_pivots(
    cnf: Sequence[Sequence[int]],
    canonical_pivots: Sequence[int],
    *,
    state_cap: int,
) -> tuple[list[int], dict[str, Any]]:
    rows, feature_work = contextual_features(cnf, canonical_pivots, state_cap=state_cap)
    ranked = sorted(rows, key=lambda r: tuple(r["rank_tuple"]))
    ordered = [int(r["var"]) for r in ranked]
    if len(ordered) != len(canonical_pivots) or set(ordered) != set(int(v) for v in canonical_pivots):
        raise AssertionError("CONTEXTUAL_SLIME_CHANGED_PIVOT_SET")
    return ordered, {
        "feature_work": feature_work,
        "rows": ranked,
        "certified_safe_pivot_count": sum(bool(r["certified_cap_safe"]) for r in rows),
    }


@contextmanager
def contextual_m2r_patch(solver_module: ModuleType) -> Iterator[dict[str, Any]]:
    original = solver_module.canonical_pivot_order
    telemetry: dict[str, Any] = {
        "pivot_order_calls": 0,
        "pivot_order_reorders": 0,
        "feature_work": 0,
        "calls_with_certified_safe_pivot": 0,
        "max_live_variables": 0,
    }

    def proposed(state, cnf=None):
        canonical = list(original(state, cnf))
        f = state.residual if cnf is None else cnf
        ordered, detail = rank_contextual_pivots(f, canonical, state_cap=state.state_cap)
        if len(ordered) != len(canonical) or set(ordered) != set(canonical):
            raise AssertionError("PIVOT_SET_CHANGED")
        telemetry["pivot_order_calls"] += 1
        telemetry["feature_work"] += int(detail["feature_work"])
        telemetry["max_live_variables"] = max(telemetry["max_live_variables"], len(canonical))
        if detail["certified_safe_pivot_count"]:
            telemetry["calls_with_certified_safe_pivot"] += 1
        if ordered != canonical:
            telemetry["pivot_order_reorders"] += 1
        return ordered

    solver_module.canonical_pivot_order = proposed
    try:
        yield telemetry
    finally:
        solver_module.canonical_pivot_order = original


def _boundary_ok(result: dict[str, Any]) -> bool:
    sb = result.get("scientific_boundary") or {}
    return (
        result.get("status") in {"SAT", "UNSAT", "OPEN"}
        and sb.get("P_VS_NP") == "OPEN"
        and sb.get("claims_p_eq_np") is False
        and sb.get("claims_p_neq_np") is False
        and sb.get("heuristic_promotion") is False
        and sb.get("general_sat_oracle") is False
        and sb.get("semantic_equivalence_oracle") is False
    )


def solve_contextual(
    solver_module: ModuleType,
    clauses: Sequence[Sequence[int]],
    *,
    cap_exponent: int = 1,
    extension_exponent: int = 0,
    bounded_resolution_width: int = 3,
) -> dict[str, Any]:
    with contextual_m2r_patch(solver_module) as telemetry:
        result = solver_module.solve_fail_closed(
            clauses,
            cap_exponent=cap_exponent,
            extension_exponent=extension_exponent,
            bounded_resolution_width=bounded_resolution_width,
        )
    if not _boundary_ok(result):
        raise TrumpCandidateError("CONTEXTUAL_M2R_EXACT_BOUNDARY_VIOLATION")
    return {
        "schema": "janus.trump.slime_contextual_m2r_r2.run.v1",
        "exact_result": result,
        "slime_telemetry": dict(telemetry),
        "candidate_result_promoted": False,
        "same_theorem_face_learning": False,
        "authority": {
            "proof_authority": False,
            "scientific_claim_promotion_authority": False,
            "command_authority": False,
            "external_effect_authority": False,
        },
        "scientific_boundary": {
            "P_VS_NP": "OPEN",
            "P_equals_NP_proved": False,
            "certified_raw_upper_is_exact_elimination_result": False,
            "heuristic_order_is_proof": False,
        },
    }


def selftest() -> dict[str, Any]:
    solver, _ = load_pinned_solver()
    formula = [[1, 2, 3], [-1, 2, 4], [1, -3, 4], [-2, -3, 4], [2, 3, -4]]
    cnf = solver.canon_cnf(formula)
    dummy_state = type("Dummy", (), {})()
    # Validate the proof-carrying upper against actual uncapped-ish eliminations.
    pivots = sorted(solver.vars_of(cnf))
    rows, _ = contextual_features(cnf, pivots, state_cap=10**9)
    for row in rows:
        out, exact = solver.eliminate_var_capped(cnf, row["var"], 10**9)
        assert out is not None
        assert exact["raw_units"] <= row["certified_raw_upper_units"]
    run = solve_contextual(solver, formula)
    assert run["exact_result"]["status"] in {"SAT", "UNSAT", "OPEN"}
    assert run["slime_telemetry"]["feature_work"] > 0
    return {
        "status": "PASS",
        "upper_bound_checked_pivots": len(rows),
        "solver_status": run["exact_result"]["status"],
        "feature_work": run["slime_telemetry"]["feature_work"],
        "P_VS_NP": "OPEN",
    }


if __name__ == "__main__":
    print(json.dumps(selftest(), indent=2, sort_keys=True))
